name: Initial LinkedIn Job Scraper

on:
  workflow_dispatch:  # Only run manually

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: main
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create config file
      run: |
        cat > config.json << 'EOL'
        {
          "proxies": {},
          "headers": {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
          },
          "search_queries": [
            {
              "keywords": "data OR analytics OR 'business intelligence'",
              "location": "Costa Rica", 
              "f_WT": ""
            }
          ],
          "desc_words": [],
          "title_exclude": [],
          "title_include": ["data", "analytics", "business intelligence"],
          "company_exclude": [],
          "languages": ["en", "es"],
          "timespan": "",
          "jobs_tablename": "jobs",
          "filtered_jobs_tablename": "filtered_jobs",
          "db_path": "./data/jobs.db",
          "pages_to_scrape": 10,
          "rounds": 1,
          "days_to_scrape": 30
        }
        EOL
        
    - name: Force initial run by removing database
      run: |
        mkdir -p data
        rm -f data/jobs.db
        
    - name: Run LinkedIn scraper
      run: |
        python main.py
        
    - name: Commit and push if there are changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        timestamp=$(date +%Y%m%d)
        
        # Add new files (force add ignored files)
        git add -f data/linkedin_jobs_*.csv
        git add -f data/*.db
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Add LinkedIn jobs data for $timestamp (initial run)"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
        fi